# Use ubuntu trusty (14.04) with sudo privileges.
dist: trusty
sudo: required
language:
  - generic
cache:
  - apt

language: cpp
compiler:
  - gcc
  
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq gcc-4.7

#check repository
script:
#brox_2004
  - cd Brox_2004
  - make
  - cd ..
#Horn_Schunk
  - cd Horn_Schunk
  - make
  - cd ..   
#Horn_Schunk_TV
  - cd Horn_Schunk_TV
  - make
  - cd .. 
#Horn_Schunk_TVbothTerms
  - cd Horn_Schunk_TVbothTerms
  - make
  - cd .. 
#Horn_Schunk_TVbothTerms_Grad
  - cd Horn_Schunk_TVbothTerms_Grad
  - make
  - cd .. 
#denoiz
  - cd denoiz
  - make
  - cd .. 




 
